### ISSUE TITLE
Adding tools for calculating properties of sections

### ISSUE THREAD

**Issue by dweiss2** [KGB33/MathTools#14]
Would it be appropriate to add tools for calculating properties of sections? I already have written for my personal use calculators for calculating section modulus, centroid, and second moment of inertia for certain shapes. If you feel these don't belong in MathTools I won't spend the time to clean them up for use.

**Comment by KGB33** [comment]
That sounds awesome. Maybe under geometry tools? Use your best judgment for the file name.
